- name: Setting up k8s on all nodes
  import_playbook: setup_kube.yml

- name: Setting up the kube
  hosts: control_nodes
  tasks:
    - name: Install kubectl
      ansible.builtin.apt:
        name: kubectl
        state: present

    - name: Install kubeadm
      ansible.builtin.apt:
        name: kubeadm
        state: present
