- name: Installing containerd
  hosts: all
  become: true
  tasks:
    - name: Including variables
      include_vars: vars/default.yml

    - name: Including binaries variables
      include_vars: vars/binaries.yml

    - name: Update apt package cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Download containerd binaries
      ansible.builtin.get_url:
        url: "{{ containerd_binaries }}"

    - name: Extract containerd binaries
      ansible.builtin.unarchive:
        src: "{{ containerd_file }}"
        dest: /usr/local

    - name: Download containerd.service
      ansible.builtin.get_url:
        url: "{{ containerd_service }}"
        dest: /etc/systemd/system/containerd.service

    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Enable now containerd containe
      ansible.builtin.systemd:
        name: containerd
        enabled: yes

    - name: Download runc
      ansible.builtin.get_url:
        url: "{{ runc_file }}"
        dest: /usr/local/sbin/runc
        mode: 0755

    - name: Download sha256sum file
      ansible.builtin.get_url:
        url: "{{ runc_checksum_file }}"
        dest: "runc.sha256sum"

    - name: Verify sha256 sum of runc
      ansible.builtin.shell: |
        cat runc.sha256sum /usr/local/sbin/runc | sha256sum -c
      register: runc_sha256

    - name: Download cni_plugins
      ansible.builtin.get_url:
        url: "{{ cni_plugins_file }}"
        dest: /tmp/setup/cni-plugins.tgz

    - name: Download cni_plugin checksum file
      ansible.builtin.get_url:
        url: "{{ cni_plugins_checksum_file }}"
        dest: "/tmp/setup/cni_plugins.sha256sum"

    - name: Verify sha256 sum of cni
      ansible.builtin.shell: |
        cat /tmp/setup/cni_plugins.sha256sum /tmp/setup/cni-plugins.tgz | sha256sum -c
      register: runc_sha256

    - name: Unarchive cni-plugins
      ansible.builtin.unarchive:
        src: /tmp/setup/cni-plugins.tgz
        dest: /opt/cni/bin

    - name: Remove temp directory
      ansible.builtin.file:
        path: /tmp/setup
        state: absent

    - name: Enable packet forwarding
      ansible.builtin.sysctl:
        name: net.ipv4.ip_forward
        value: 1
        state: present
        reload: yes
