- name: Setting up the k8s
  hosts: all

- name: Setting up containerd on all nodes
  import_playbook: setup_containerd.yml

- name: Setting up kubelet on all nodes
  import_playbook: setup_kubelet.yml

- name: Init cluster
  hosts: control_nodes
  become: yes
  tasks:
    - name: Include variables
      include_vars: vars/jumpbox.yml

    - name: Reset kubeadm
      shell: kubeadm reset -f

    - name: Start cluster
      shell: kubeadm init --pod-network-cidr=10.30.0.0/16

    - name: Create ~/.kube directory
      file:
        path: ~/.kube
        state: directory

    - name: Copy admin config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: ~/.kube/config
        remote_src: true

    - name: Ensure that clutser directory exists on jumpbox
      file:
        path: "{{ cluster_directory }}"
        state: directory

    - name: Check if join command already exists
      stat:
        path: "{{ cluster_join_command_file }}"
      register: join_file_status

    - name: Get join token
      when: not join_file_status.stat.exists
      shell: kubeadm token create --print-join-command
      register: cluster_join_command

    - name: Copy join command to local file.
      local_action: copy content="{{ cluster_join_command.stdout_lines[0] }}" dest="/tmp/cluster_join_command" mode=0777

- name: Install Cilium on control nodes
  hosts: control_nodes
  tasks:
    - name: Download Cilium CLI
      get_url:
        url: "https://github.com/cilium/cilium-cli/releases/download/v0.16.7/cilium-linux-arm64.tar.gz"
        dest: /tmp/cilium.tar.gz 
        mode: 0755

    - name: Extract Cilium CLI
      unarchive:
        src: /tmp/cilium.tar.gz
        dest: /usr/local/bin
        remote_src: true

    - name: Install Cilium
      shell:
        cmd: cilium install --version 1.15.4

- name: Join workers
  hosts: worker_nodes
  become: true
  tasks:
    - name: Copy join cluster command
      copy: 
        src: /tmp/cluster_join_command
        dest: /tmp/cluster_join_command
        mode: 0777
   
    - name: Reset kubeadm to be sure
      shell:
        cmd: kubeadm reset -f


    - name: Join cluster
      shell:
        cmd: sh /tmp/cluster_join_command
